/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ChaserRouteImport } from './routes/chaser'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuotesIndexRouteImport } from './routes/quotes.index'
import { Route as ClientsIndexRouteImport } from './routes/clients.index'
import { Route as RequestProIdRouteImport } from './routes/request.$proId'
import { Route as QuotesNewRouteImport } from './routes/quotes.new'
import { Route as QuotesQuoteIdRouteImport } from './routes/quotes.$quoteId'
import { Route as PortalTokenRouteImport } from './routes/portal.$token'
import { Route as InvoicesQuoteIdRouteImport } from './routes/invoices.$quoteId'
import { Route as ClientsNewRouteImport } from './routes/clients.new'
import { Route as ClientsClientIdRouteImport } from './routes/clients.$clientId'
import { Route as CaptureNewRouteImport } from './routes/capture.new'
import { Route as CaptureCaptureIdRouteImport } from './routes/capture.$captureId'
import { Route as PortalCCodeRouteImport } from './routes/portal.c.$code'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaserRoute = ChaserRouteImport.update({
  id: '/chaser',
  path: '/chaser',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesIndexRoute = QuotesIndexRouteImport.update({
  id: '/quotes/',
  path: '/quotes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestProIdRoute = RequestProIdRouteImport.update({
  id: '/request/$proId',
  path: '/request/$proId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesNewRoute = QuotesNewRouteImport.update({
  id: '/quotes/new',
  path: '/quotes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesQuoteIdRoute = QuotesQuoteIdRouteImport.update({
  id: '/quotes/$quoteId',
  path: '/quotes/$quoteId',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalTokenRoute = PortalTokenRouteImport.update({
  id: '/portal/$token',
  path: '/portal/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesQuoteIdRoute = InvoicesQuoteIdRouteImport.update({
  id: '/invoices/$quoteId',
  path: '/invoices/$quoteId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsNewRoute = ClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureNewRoute = CaptureNewRouteImport.update({
  id: '/capture/new',
  path: '/capture/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureCaptureIdRoute = CaptureCaptureIdRouteImport.update({
  id: '/capture/$captureId',
  path: '/capture/$captureId',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalCCodeRoute = PortalCCodeRouteImport.update({
  id: '/portal/c/$code',
  path: '/portal/c/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/chaser': typeof ChaserRoute
  '/insights': typeof InsightsRoute
  '/messages': typeof MessagesRoute
  '/pricing': typeof PricingRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/welcome': typeof WelcomeRoute
  '/capture/$captureId': typeof CaptureCaptureIdRoute
  '/capture/new': typeof CaptureNewRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/new': typeof ClientsNewRoute
  '/invoices/$quoteId': typeof InvoicesQuoteIdRoute
  '/portal/$token': typeof PortalTokenRoute
  '/quotes/$quoteId': typeof QuotesQuoteIdRoute
  '/quotes/new': typeof QuotesNewRoute
  '/request/$proId': typeof RequestProIdRoute
  '/clients/': typeof ClientsIndexRoute
  '/quotes/': typeof QuotesIndexRoute
  '/portal/c/$code': typeof PortalCCodeRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/chaser': typeof ChaserRoute
  '/insights': typeof InsightsRoute
  '/messages': typeof MessagesRoute
  '/pricing': typeof PricingRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/welcome': typeof WelcomeRoute
  '/capture/$captureId': typeof CaptureCaptureIdRoute
  '/capture/new': typeof CaptureNewRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/new': typeof ClientsNewRoute
  '/invoices/$quoteId': typeof InvoicesQuoteIdRoute
  '/portal/$token': typeof PortalTokenRoute
  '/quotes/$quoteId': typeof QuotesQuoteIdRoute
  '/quotes/new': typeof QuotesNewRoute
  '/request/$proId': typeof RequestProIdRoute
  '/clients': typeof ClientsIndexRoute
  '/quotes': typeof QuotesIndexRoute
  '/portal/c/$code': typeof PortalCCodeRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/chaser': typeof ChaserRoute
  '/insights': typeof InsightsRoute
  '/messages': typeof MessagesRoute
  '/pricing': typeof PricingRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/welcome': typeof WelcomeRoute
  '/capture/$captureId': typeof CaptureCaptureIdRoute
  '/capture/new': typeof CaptureNewRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/new': typeof ClientsNewRoute
  '/invoices/$quoteId': typeof InvoicesQuoteIdRoute
  '/portal/$token': typeof PortalTokenRoute
  '/quotes/$quoteId': typeof QuotesQuoteIdRoute
  '/quotes/new': typeof QuotesNewRoute
  '/request/$proId': typeof RequestProIdRoute
  '/clients/': typeof ClientsIndexRoute
  '/quotes/': typeof QuotesIndexRoute
  '/portal/c/$code': typeof PortalCCodeRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/calendar'
    | '/chaser'
    | '/insights'
    | '/messages'
    | '/pricing'
    | '/search'
    | '/settings'
    | '/welcome'
    | '/capture/$captureId'
    | '/capture/new'
    | '/clients/$clientId'
    | '/clients/new'
    | '/invoices/$quoteId'
    | '/portal/$token'
    | '/quotes/$quoteId'
    | '/quotes/new'
    | '/request/$proId'
    | '/clients/'
    | '/quotes/'
    | '/portal/c/$code'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/calendar'
    | '/chaser'
    | '/insights'
    | '/messages'
    | '/pricing'
    | '/search'
    | '/settings'
    | '/welcome'
    | '/capture/$captureId'
    | '/capture/new'
    | '/clients/$clientId'
    | '/clients/new'
    | '/invoices/$quoteId'
    | '/portal/$token'
    | '/quotes/$quoteId'
    | '/quotes/new'
    | '/request/$proId'
    | '/clients'
    | '/quotes'
    | '/portal/c/$code'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/calendar'
    | '/chaser'
    | '/insights'
    | '/messages'
    | '/pricing'
    | '/search'
    | '/settings'
    | '/welcome'
    | '/capture/$captureId'
    | '/capture/new'
    | '/clients/$clientId'
    | '/clients/new'
    | '/invoices/$quoteId'
    | '/portal/$token'
    | '/quotes/$quoteId'
    | '/quotes/new'
    | '/request/$proId'
    | '/clients/'
    | '/quotes/'
    | '/portal/c/$code'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CalendarRoute: typeof CalendarRoute
  ChaserRoute: typeof ChaserRoute
  InsightsRoute: typeof InsightsRoute
  MessagesRoute: typeof MessagesRoute
  PricingRoute: typeof PricingRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  WelcomeRoute: typeof WelcomeRoute
  CaptureCaptureIdRoute: typeof CaptureCaptureIdRoute
  CaptureNewRoute: typeof CaptureNewRoute
  ClientsClientIdRoute: typeof ClientsClientIdRoute
  ClientsNewRoute: typeof ClientsNewRoute
  InvoicesQuoteIdRoute: typeof InvoicesQuoteIdRoute
  PortalTokenRoute: typeof PortalTokenRoute
  QuotesQuoteIdRoute: typeof QuotesQuoteIdRoute
  QuotesNewRoute: typeof QuotesNewRoute
  RequestProIdRoute: typeof RequestProIdRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
  QuotesIndexRoute: typeof QuotesIndexRoute
  PortalCCodeRoute: typeof PortalCCodeRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chaser': {
      id: '/chaser'
      path: '/chaser'
      fullPath: '/chaser'
      preLoaderRoute: typeof ChaserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes/': {
      id: '/quotes/'
      path: '/quotes'
      fullPath: '/quotes/'
      preLoaderRoute: typeof QuotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request/$proId': {
      id: '/request/$proId'
      path: '/request/$proId'
      fullPath: '/request/$proId'
      preLoaderRoute: typeof RequestProIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes/new': {
      id: '/quotes/new'
      path: '/quotes/new'
      fullPath: '/quotes/new'
      preLoaderRoute: typeof QuotesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes/$quoteId': {
      id: '/quotes/$quoteId'
      path: '/quotes/$quoteId'
      fullPath: '/quotes/$quoteId'
      preLoaderRoute: typeof QuotesQuoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$token': {
      id: '/portal/$token'
      path: '/portal/$token'
      fullPath: '/portal/$token'
      preLoaderRoute: typeof PortalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/$quoteId': {
      id: '/invoices/$quoteId'
      path: '/invoices/$quoteId'
      fullPath: '/invoices/$quoteId'
      preLoaderRoute: typeof InvoicesQuoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/new': {
      id: '/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof ClientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture/new': {
      id: '/capture/new'
      path: '/capture/new'
      fullPath: '/capture/new'
      preLoaderRoute: typeof CaptureNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture/$captureId': {
      id: '/capture/$captureId'
      path: '/capture/$captureId'
      fullPath: '/capture/$captureId'
      preLoaderRoute: typeof CaptureCaptureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/c/$code': {
      id: '/portal/c/$code'
      path: '/portal/c/$code'
      fullPath: '/portal/c/$code'
      preLoaderRoute: typeof PortalCCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CalendarRoute: CalendarRoute,
  ChaserRoute: ChaserRoute,
  InsightsRoute: InsightsRoute,
  MessagesRoute: MessagesRoute,
  PricingRoute: PricingRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  WelcomeRoute: WelcomeRoute,
  CaptureCaptureIdRoute: CaptureCaptureIdRoute,
  CaptureNewRoute: CaptureNewRoute,
  ClientsClientIdRoute: ClientsClientIdRoute,
  ClientsNewRoute: ClientsNewRoute,
  InvoicesQuoteIdRoute: InvoicesQuoteIdRoute,
  PortalTokenRoute: PortalTokenRoute,
  QuotesQuoteIdRoute: QuotesQuoteIdRoute,
  QuotesNewRoute: QuotesNewRoute,
  RequestProIdRoute: RequestProIdRoute,
  ClientsIndexRoute: ClientsIndexRoute,
  QuotesIndexRoute: QuotesIndexRoute,
  PortalCCodeRoute: PortalCCodeRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
